### PR TITLE
STL concepts and resources

### PR DESCRIPTION
**Pull request by sanju6890**
Added introduction to **STL** and its components & links to resources.

### CODE REVIEW

**Comment by KaushikiKrity** [comment]
@sanju6890  I cannot access the resources would you check once.

**Comment by sanju6890** [comment]
hi @kaushikikrityy It's a pdf file and I have added links to online resources below the components' title. 
Please open the pdf file, you will be able see the resource's links.
Kindly check through the link below 👇
[https://github.com/sanju6890/hello_C_language/blob/master/C%2B%2B%20STL.pdf](url)

**Review by sanju6890 — COMMENTED** [review]
Added a C++ program to illustrate the working of a very important STL concept i.e. Vectors.

**Comment by KaushikiKrity** [comment]
> hi @kaushikikrityy It's a pdf file and I have added links to online resources below the components' title.
> Please open the pdf file, you will be able see the resource's links.
> Kindly check through the link below 👇
> [https://github.com/sanju6890/hello_C_language/blob/master/C%2B%2B%20STL.pdf](url)

It's leading to show error.

**Comment by sanju6890** [comment]
Hi @kaushikikrityy I have deleted the previous file and updated the information in a new .txt file.
Kindly Check, Please.

**Comment by sanju6890** [comment]
Hello @kaushikikrityy I have done some changes to my contributions, please review it and confirm, if it's fine.
Happy Coding :)

**Comment by KaushikiKrity** [comment]
@sanju6890  good work!

**Pull request merged**
