### PR TITLE
I have added a Guideline file and some books for cpp.Resolved #7

### LINKED ISSUE #7: Add a guide file to start learning C++ language.
Add links , tutorials or some guide how to start C++ .
Also give a brief description to why this language is essential.
There is already a file existing you  can contribute to this issue but please make sure that there is a file hello_C_language/guide file to start learning C++ language. make sure you contribute under this . Try to add some additional information.

### PR DESCRIPTION
**Pull request by mayu12525**
**Description**

I have added guideline file for cpp and added some books for cpp.

### CODE REVIEW

**Comment by KaushikiKrity** [comment]
@mayu12525 you  can contribute to this issue but please make sure that there is a file hello_C_language/guide file to start learning C++ language. make sure you contribute under this . Try to add some additional information. 
Any queries please confirm before committing. Thank you.

**Comment by mayu12525** [comment]
> @mayu12525 you can contribute to this issue but please make sure that there is a file hello_C_language/guide file to start learning the C++ language. make sure you contribute under this. Try to add some additional information.
> Any queries please confirm before committing. Thank you.

@kaushikikrityy ok I am working on this issue. After resolving this I will make changes according to #17

**Comment by mayu12525** [comment]
> @mayu12525 you can contribute to this issue but please make sure that there is a file hello_C_language/guide file to start learning the C++ language. make sure you contribute under this. Try to add some additional information.
> Any queries please confirm before committing. Thank you.

Also, we have the option to add the guidelines in Readme.md file. should I go with this approach or follow the previous approach?

**Comment by KaushikiKrity** [comment]
@mayu12525 sounds cool .

**Comment by mayu12525** [comment]
> @mayu12525 sounds cool .

so should I add the guidelines in Readme.md?

**Comment by KaushikiKrity** [comment]
@mayu12525 if you feel that it would help you in your work the go ahead.

**Pull request closed without merging**
